USE [master]
GO

/****** Object:  Database [SimpleForum]    Script Date: 12/29/2017 6:14:32 PM ******/
CREATE DATABASE [SimpleForum]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimpleForum', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleForum.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SimpleForum_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleForum_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SimpleForum] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleForum].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SimpleForum] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SimpleForum] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SimpleForum] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SimpleForum] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SimpleForum] SET ARITHABORT OFF 
GO

ALTER DATABASE [SimpleForum] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SimpleForum] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SimpleForum] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SimpleForum] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SimpleForum] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SimpleForum] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SimpleForum] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SimpleForum] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SimpleForum] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SimpleForum] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SimpleForum] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SimpleForum] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SimpleForum] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SimpleForum] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SimpleForum] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SimpleForum] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SimpleForum] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SimpleForum] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SimpleForum] SET  MULTI_USER 
GO

ALTER DATABASE [SimpleForum] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SimpleForum] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SimpleForum] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SimpleForum] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SimpleForum] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SimpleForum] SET  READ_WRITE 
GO


USE [SimpleForum]
GO

/****** Object:  Table [dbo].[Posts]    Script Date: 12/29/2017 6:15:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Posts
CREATE TABLE [dbo].[Posts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Description] [nvarchar](400) NOT NULL,
	[TopicId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Posts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Posts]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Posts_dbo.Topics_TopicId] FOREIGN KEY([TopicId])
REFERENCES [dbo].[Topics] ([Id])
GO

ALTER TABLE [dbo].[Posts] CHECK CONSTRAINT [FK_dbo.Posts_dbo.Topics_TopicId]
GO

ALTER TABLE [dbo].[Posts]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Posts_dbo.Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Posts] CHECK CONSTRAINT [FK_dbo.Posts_dbo.Users_UserId]
GO


-- Topics
CREATE TABLE [dbo].[Topics](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NULL,
	[Description] [nvarchar](400) NULL,
	[Date] [datetime] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Topics] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Topics]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Topics_dbo.Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Topics] CHECK CONSTRAINT [FK_dbo.Topics_dbo.Users_UserId]
GO


-- Users
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_dbo.Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO